# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane
default_platform(:android)

platform :android do
  desc "Runs all the tests"
  lane :test do
    gradle(task: "test")
  end

  desc "Submit a new Beta Build to Crashlytics Beta"
  lane :qc do
    increment_version_code(
            gradle_file_path: "app/build.gradle",
            #ext_constant_name: "test"
            #app_folder_name:"app"
     )
     build_android_app(task: "assembleQcDebug")
     firebase_app_distribution(
        app: "1:647746340483:android:837a15184ce57f675bbdb6",
        testers: "rissmon@gmail.com",
        release_notes: "",
        firebase_cli_path:"C:/Users/RISSMON/AppData/Roaming/npm/firebase",
    )

    # sh "your_script.sh"
    # You can also use other beta testing services here
  end

  desc "Deploy a new version to the Google Play"
  lane :deploy do
    gradle(task: "clean assembleRelease")
    upload_to_play_store
  end
end